### ISSUE TITLE
Stellar Transformations missing first chapter of every volume

### ISSUE THREAD

**Issue by ceranco** [EternalTrail/Novel-2-EBook#1]
**Describe the bug**
The book `Stellar Transformations` is missing the first chapter of every volume (from the second volume and on).

**To Reproduce**
1. Go to 'Select Website -> Wuxia World'
2. Go to 'Select Novel -> Stellar Transformations'
3. Enable 'Download Separate Chapters'
4. Choose 'Select Starting Chapter -> `Book 2 Chapter 1`
5. Choose 'Select Ending Chapter -> `Book 2 Chapter 24`
6. Click 'Download'
7. View epub in Calibre: The first chapter is empty.

**Expected behavior**
The first chapter should not be empty.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7.3

**Additional context**
I really appreciate you maintaining this awesome project, and I use it regularly. Thanks!

**Comment by EternalTrail** [comment]
This issue has been fixed (13f5b58), you can find the updated windows binaries in the [release](https://github.com/EternalTrail/Novel-2-EBook/releases) section.

**Comment by ceranco** [comment]
I can confirm that the problem was fixed!

Thank you very much 😄
