### ISSUE TITLE
Adding new novel source

### ISSUE THREAD

**Issue by wagnerfranklin** [EternalTrail/Novel-2-EBook#3]
I would really appreciate if you added https://readnovelfull.com/ to the source sites. I tried to change the script but it didn't work on python 3.9 .

**Comment by EternalTrail** [comment]
This website is too difficult to parse in that I can't get the full list of novels for it easily, but that's not even the biggest issue. The biggest issue is that even if I got the list of novels, if you go to the novels page on this website the list of chapters is loaded in dynamically which means that a browser needs to be used which requires complete rework of the program, and thus I won't be adding this website. Alternatively, you can use the Read Light Novel website which is a part of this program and it should contain most of the novels you can find online.
